components:
  schemas:
    Product:
      type: object
      properties:
        _id:
          type: ObjetId
        code:
          type: String
          description: Id autogeneration of Mongo
        product_name:
          type: String
        description:
          type: String
        price:
          type: Number
        offer:
          type: Number
        stock:
          type: Number
        image:
          type: String
      example:
        _id: ObjectId('636b957b8d4ab97dec21f392')
        product_name: 1
        code: 1
        description: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam tristique mauris ultricies varius finibus.
        quantity: 1
        price: 1
        image: /images/product.png
        __v: 0
            
paths:
  /api/product/:
    get:
      summary: get all user of bd
      tags:
        - Products
      responses:
        200:
          description: get all products ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'

